### ISSUE TITLE
Introduce asynchronous processing environment

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#13]
Most likely celery.  We want to be able to break the following tasks out into an asynchronous processing chain:

1. convert the spreadsheet into a job
2. run each identifier through the EPMC detection process
3. trigger the OAG integration layer

After (3) the chain will end, and the OAGR client will trigger the remaining operations on completion.  That is:

1. Email the user to tell them their job has completed

**Comment by emanuil-tolev** [comment]
Try huey or another very simple processing system since it's essentially a daemon. But if it takes longer than 30 min to do in a production-ready way, copy daemon setup from oagr.

**Comment by emanuil-tolev** [comment]
@richard-jones Could you point me at the daemonisation code in OAGR? https://github.com/CottageLabs/oagr/tree/master/portality doesn't seem to contain a while True or any terminal detachment code, but maybe I just can't find it :).

Basically I'm a bit hesitant to introduce a new dependency (Redis) for such a small project, where we could let it run forever and then it eventually blows up.. on the other hand we do need to learn how to do this **** but if the project can be served alright by 1 python script running a while True loop under supervisor, then maybe we should limit ourselves to that first.

**Comment by emanuil-tolev** [comment]
To clarify: Huey is much, much simpler than celery, but does need somewhere to store the queue info.

See example at http://huey.readthedocs.org/en/latest/getting-started.html

**Comment by emanuil-tolev** [comment]
> @richard-jones Could you point me at the daemonisation code in OAGR? https://github.com/CottageLabs/oagr/tree/master/portality doesn't seem to contain a while True or any terminal detachment code, but maybe I just can't find it :).

It's in octopus - no need to look into this. I'll continue with the work on this issue.

https://github.com/richard-jones/magnificent-octopus/blob/da8520172b07af8604897e470e21900408f87722/octopus/modules/oag/oagr.py#L74

**Comment by richard-jones** [comment]
Actual initialisation of the daemon is done from this script:

https://github.com/richard-jones/magnificent-octopus/blob/da8520172b07af8604897e470e21900408f87722/octopus/modules/oag/runner.py


On 8 January 2015 at 20:22, Emanuil Tolev <notifications@github.com> wrote:

> @richard-jones <https://github.com/richard-jones> Could you point me at
> the daemonisation code in OAGR?
> https://github.com/CottageLabs/oagr/tree/master/portality doesn't seem to
> contain a while True or any terminal detachment code, but maybe I just
> can't find it :).
>
> It's in octopus - no need to look into this. I'll continue with the work
> on this issue.
>
>
> https://github.com/richard-jones/magnificent-octopus/blob/da8520172b07af8604897e470e21900408f87722/octopus/modules/oag/oagr.py#L74
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CottageLabs/oacwellcome/issues/13#issuecomment-69242816>
> .
>



-- 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by richard-jones** [comment]
Ok, so the only thing to decide is whether at this stage we want to introduce a new, less-well-understood bit of infrastructure, or whether we just daemonise the whole thing, and have it pull tasks off the ES instance.

**Comment by emanuil-tolev** [comment]
> whether we just daemonise the whole thing, and have it pull tasks off the ES instance.

I am gunning for this option. Sorry if I didn't make it clear above.

**Comment by richard-jones** [comment]
Also, worth putting a facetview somewhere so that we can see jobs in the system

**Comment by emanuil-tolev** [comment]
Put up a facetview for admin view of all processing spreadsheets as part of this.

**Comment by emanuil-tolev** [comment]
Added an extremely simple runner at https://github.com/CottageLabs/oacwellcome/blob/develop/service/runner.py . Leaving issue open to add facetview.

**Comment by richard-jones** [comment]
Also, see #66 - I will look at a fix on the back-end ( #67 ), but we should also make the runner more resilient to errors

**Comment by richard-jones** [comment]
Actually, I'm going to open another issue for the facetview stuff, as I think we need to do just a little more than throw a fv over the top of the job index, so will track is separately

**Comment by emanuil-tolev** [comment]
OK - I'm in the middle of adding that, so feel free to open another one. Do we need to keep this one open then?
