### ISSUE TITLE
Normalise identifiers

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#14]
For the full service we will need to ensure that the identifiers that we get given in the PMCID, PMID and DOI columns of the spreadsheet are normalised for consistent reference.  We should therefore have normalisation routines for each of these which are applied whenever an identifier is recorded.

PMCID: all PMCIDs should start with the string PMC
PMID: should be a numeric string of 1 - 8 digits
DOI: should start with just "10."

Note that there is already code in OAG that can do some or all of this, so it should be copied from there and potentially included as a function in portentious.

**Comment by richard-jones** [comment]
@Nimphal - could you just review again the PMCID normalisation for me, we need to make it a bit more aggressive (relates to the comment above, too).  Somewhere @emanuil-tolev has the rules for what constitutions a PMCID, and if we could throw out any that don't meet those criteria, that would be great.

**Comment by emanuil-tolev** [comment]
Rules for what a PMCID is:
https://github.com/CottageLabs/oacwellcome/issues/15#issuecomment-68896793

OpenArticleGauge code for PMCID support (this is the regex used to validate them, with notes on what's valid):
https://github.com/CottageLabs/OpenArticleGauge/blob/dev/openarticlegauge/plugins/epmc.py#L15

This is how you use the regex: https://github.com/CottageLabs/OpenArticleGauge/blob/dev/openarticlegauge/plugins/epmc.py#L45

Just checking if the result of re.match is None or not is sufficient to know whether your string is a valid PMCID or not (None means it's not valid).

**Comment by Nimphal** [comment]
See https://github.com/richard-jones/magnificent-octopus/pull/5

**Comment by emanuil-tolev** [comment]
> See richard-jones/magnificent-octopus#5

you'll need to bump the octopus version in oacwellcome now that that PR is accepted

**Comment by richard-jones** [comment]
excellent.  I've updated the octopus version in the submodule.
