### ISSUE TITLE
Add EPMC web page scrape plugin to OAG

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#16]
We require a detect provider plugin for OAG which can download content from an EPMC web page (not the XML) and mine for two things:

1. The licence
2. Whether the item is an author manuscript or not

Two examples of articles which are author manuscripts are:

http://europepmc.org/articles/PMC4160115
http://europepmc.org/articles/PMC4132119

They each have a logo on the page which identifies it as an author manuscript:

```html
<img usemap="#logo-imagemap" alt="" src="/corehtml/pmc/pmcgifs/logo-nihpa.gif"></img>
```

or

```html
<img usemap="#logo-imagemap" alt="Logo of wtpa" src="/corehtml/pmc/pmcgifs/logo-wtpa2.gif"></img>
```

In order to collect this information we will have to extend the OAG data model to include the data in the response, see #17

**Comment by emanuil-tolev** [comment]
We *must* do the web page here. If there's time we can include the code from the WOAC app that uses the API too #40

**Comment by richard-jones** [comment]
Yes, but the call to the XML api should be done outside the scope of this project.  Web page is the only thing that matters to deliver this project.

**Comment by emanuil-tolev** [comment]
Was going to ask Robert and Cecy for an example, but decided to actually just ask the EPMC help desk. Then while writing to them I realised I might well look to see if their OAI service can't give me an example open article, so I can see the license statement.

Turns out one of the examples on their OAI service page is an open article:

http://europepmc.org/articles/PMC2654146

It does have the license text in the HTML.

**Comment by emanuil-tolev** [comment]
> ```<img usemap="#logo-imagemap" alt="" src="/corehtml/pmc/pmcgifs/logo-nihpa.gif"></img>```

This doesn't work anymore. I think "Author Manuscript; Accepted for publication in peer reviewed journal" is sufficient (that's what forms part of that picture you're referring to, 'cept they've changed the picture file names so it's wiser to go by the alt text I feel).

> ```<img usemap="#logo-imagemap" alt="Logo of wtpa" src="/corehtml/pmc/pmcgifs/logo-wtpa2.gif"></img>```

Can't find that either. We could go with just the picture, though to be honest we should just use the file name in that case, no need to break it if they decide to move the image. But additionally I think this is sufficient, having looked at the page: "Author manuscript; available in PMC"

**Comment by emanuil-tolev** [comment]
This is done.

But .. I can't find any articles which are both OA and are an author's manuscript. Even with using the uber advanced EPMC search abilities. Magically all "cc" or "cc-by" articles are normal publications.

Which means that right now OAG records the license as ```failed-to-obtain-license```, which is a generic thing added by OAG itself, not the plugins. So on the articles that are author manuscripts we don't get information about the fact that they are author manuscripts.

This won't do so I'm looking for a solution atm.

**Comment by emanuil-tolev** [comment]
> Which means that right now OAG records the license as failed-to-obtain-license, which is a generic thing added by OAG itself, not the plugins. So on the articles that are author manuscripts we don't get information about the fact that they are author manuscripts.
> 
> This won't do so I'm looking for a solution atm.

Well, the reason OAG can't find a license is because the articles which are author manuscripts are under default copyright. So .. there is no license, legally, so there's no text.

Which means the license is Other (Not open). Which is what I specified in the EPMC config: http://howopenisit.org/publisher/83692980e8104ee8864941ff186c96cc .

Now it works - we can identify somewhat reliably which articles are author manuscripts, even if they have no legal license: http://howopenisit.org/lookup/PMC4160115.json .

**Comment by emanuil-tolev** [comment]
Closing this, since it's all tested and so forth (the tests took me a few hours in fact..). Feel free to reopen if you encounter problems.

**Comment by emanuil-tolev** [comment]
> Well, the reason OAG can't find a license is because the articles which are author manuscripts are under default copyright. So .. there is no license, legally, so there's no text.
> 
> Which means the license is Other (Not open). Which is what I specified in the EPMC config: http://howopenisit.org/publisher/83692980e8104ee8864941ff186c96cc .

This isn't great, since the license was still a failure, and OACWellcome won't proceed to try to fetch the license via other means.

**Comment by emanuil-tolev** [comment]
> This isn't great, since the license was still a failure, and OACWellcome won't proceed to try to fetch the license via other means.

But we don't want to fetch the license via other ID-s, because it's been definitively established as a closed license (or no license - default copyright).
