### ISSUE TITLE
Extend the OAG data model to support identification of author manuscript

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#17]
Propose to put this in license.provenance.author_manuscript, so as not to be confused with the licence detection itself.  Then any plugin which happens to recognise this can populate it.

This will involve

1. updating the site documentation
2. updating the functions which write licences to the data model
3. updating any plugins which might want to use this (only the EPMC one at this stage)

**Comment by emanuil-tolev** [comment]
> This is what I've done for testing purposes for the prototype, so if this changes we just need to synchronise the new decision with the existing tests

Nope, is fine. Though I would have recorded it under licence directly, as that's where decisions go. Provenance is more about the source, not a decision based on something in the source (that's what all the siblings of provenance are). But I'll leave it there right now.

**Comment by emanuil-tolev** [comment]
Done.

**Comment by emanuil-tolev** [comment]
http://howopenisit.org/lookup/PMC2654146.json

**Comment by emanuil-tolev** [comment]
Consider adding this in a whole new section for plugins to add extra info to.
