### ISSUE TITLE
Production Server

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#20]
For live deployment.  Flesh this out towards the end of the project.

**Comment by emanuil-tolev** [comment]
Which size server is the question here.

We can get by quite easily on 2GB RAM as long as not many queries are issued against the index. Not sure if this app issues any big queries at all. OAGR? Its admin interface only issues them from time to time so I wouldn't be worried.

Another thing is size of the index. I expect we'll stay well below 10GB, correct me if wrong.

If these are correct I'll recommend a server size and start on it after today's tech meeting.

**Comment by emanuil-tolev** [comment]
Also add newrelic to the app when running it on live

**Comment by emanuil-tolev** [comment]
@Steven-Eardley is helping with this - he's made the server, looks great :). Hammered it out of the fire of a thousand burning wrongly licensed publisher article pages. He and I will set up the app on there the coming Tuesday, and then it should be all pretty much done in terms of live service. Backups will be the only addition.

**Comment by emanuil-tolev** [comment]
http://compliance.cottagelabs.com is the live server's place

**Comment by markmacgillivray** [comment]
Has there been any quoting for this on a production server? Is there
potential to use the cluster index for this one? Discussion required
perhaps.

**Comment by emanuil-tolev** [comment]
Yep, was quoted and I am just about to invoice for hosting. Can use a cluster, yeah. It's currently not an app used by many users, sort of more Wellcome-internal. There are plans to potentially make it into something scholars use, then it will definitely need to use a cluster.

**Comment by markmacgillivray** [comment]
Didn't the quoting process involve considering server size?

**Comment by emanuil-tolev** [comment]
> Didn't the quoting process involve considering server size?

Yep, for now it's just the one small machine. It's not a big app, with very few users. It's on the Growing tier at http://cottagelabs.com/operations/service . There should be enough to cover a small cluster of 2 machines of the size specified above (2GB RAM) and an app server of 1GB, even if we do go with upgrading it. It doesn't really warrant the Established tier yet, regardless of the exact setup behind it.

**Comment by emanuil-tolev** [comment]
Write a fabric script that deploys and restarts everything nicely on production server.

**Comment by emanuil-tolev** [comment]
> Write a fabric script that deploys and restarts everything nicely on production server.

Done. All production server configs are tested and now sit in the sysadmin repo, we're ready for long-term maintenance.
