### ISSUE TITLE
Add ability to lookup code to do incremental re-try

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#25]
Sometimes APIs will not respond in time.  We need to consider building in incremental retrying into the request process to handle this cleanly.

**Comment by emanuil-tolev** [comment]
We should take this from OAG as per the above for now. Leave writing an adapter for requests for later.

**Comment by richard-jones** [comment]
I've taken the functions from OAG and added some extra bells and whistles, and there's a PR request open for it.  All seems to be working, although a lot of effort to truly test.  Have tested timeouts, though, and they are all working correctly.  Closing.
