### ISSUE TITLE
[OAG] ensure that licences are consistently named

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#36]
In particular, CC BY-NC-ND licences can be detected as cc-nc-nd OR cc-by-nc-nd

**Comment by emanuil-tolev** [comment]
Currently cc-by-nc-nd is aliased to cc-nc-nd. It should be the other way around, or cc-nc-nd should be ideally removed entirely and replaced with cc-by-nc-nd in the whole OAG codebase / GSM configs.

**Comment by emanuil-tolev** [comment]
Haven't done this yet. Need to search across the uploaded configs on howopenisit.org to see if anybody is using the license I'm about to remove, so held up by this (and prioritising something else on the project). Hope to have done by Friday.

**Comment by emanuil-tolev** [comment]
done on this side
