### ISSUE TITLE
OAG response not always directly correlated with request

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#52]
OAG aggressively caches responses to requests for identifiers.  It also canonicalises incoming identifiers and uses the canonical form to refer to the response throughout the request and in the cache.

Two identifiers which are "the same" (such as a DOI which starts "10." or a DOI which starts with "http://dx.doi.org/10." can be canonicalised to a single canonical representation ("doi:10." in OAG).

If two sequential requests are made to OAG for this DOI in its two different forms, the response in the second case will be identical to the response in the first case, as they both canonicalise to the same form, and that is what the cached version is served as.

But identical responses is /bad/ because the requests are not identical, the "id" portion is a different string.

Therefore, the response in the second case cannot trivially be related to the request that resulted in that response at the caller's end, because the passed "id" is not the same as the response "id".  

They would need to know OAG's canonicalisation routine, run it on their own identifiers, and compare the "canonical" response.

**Comment by richard-jones** [comment]
Agreed that the initial work on this will be:

* rewrite the id from a cached record in the response from OAG with the ID requested by the user
* rewrite the id from an archived record in the response from OAG with the ID requested by the user

**Comment by emanuil-tolev** [comment]
I've rolled out a fix to http://howopenisit.org . Leaving open to just remember to test it.

**Comment by emanuil-tolev** [comment]
Wow, this is ridiculous.

> Nop . It is can not be refereed to as "available" nor "reliable" .

> undependable, untrustworthy, irresponsible, fickle, capricious, irregular, erratic, unpredictable, inconstant, mutable, slippery, fragile and arbitrary might be more accurate description ( all together and also each separately ).

> China´s internet and communications regulations and laws are vigorously implemented by provincial political branches of state-owned ISPs, business companies, and organizations - each implementing it´s own censorship systems as it see fit .

> These systems are also periodically updated in relation to current political or geopolitical events. For example, in the week of a party summit , the censorship is much more strict and the systems get "hardened". Another example is the transition period between governments ( also local ) or the hosting of world wide events like the olympics, Asia games etc . again - those changes are LOCAL and PERIODICAL.

I'm going to start serving a minified version of jquery to people who *fail* to get it from the Google CDN (and additionally I might change the CDN to another good one, to try to avoid having to serve jQuery to everybody in China ourselves).

Even if it does result in somewhat increased bandwidth, I do strongly feel we should at least give it a go and simply monitor the bandwidth situation.

**Comment by emanuil-tolev** [comment]
My fix doesn't seem to work, will investigate.

**Comment by emanuil-tolev** [comment]
OK, working now. Problem was we store the identifier in the OAG response in more than one place. Not all of these were being updated. Also was appending the identifier object to the record like this: "id" : {identifier: blah blah, canonical: blah, type: doi}, where the intention was to just get the string.

May have caused some circular reference problems *cough*, so these may be resolved now too.

Closing this issue as it's easy to test:

1. go to http://howopenisit.org , put in 10.1371/journal.pone.0048753
2. now refresh page, put in doi:10.1371/journal.pone.0048753
3. previously it'd give you back 10.1371/journal.pone.0048753 instead of the doi-prefixed one. But now it works correctly.
