### ISSUE TITLE
Handle CC0 correctly

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#63]
* Be able to detect CC0 from EPMC (how - what URL/type do they refer to it by?)
* factor CC0 into compliance decision (it is equal to being CC-BY)

**Comment by richard-jones** [comment]
See examples of articles which have CC0, and determine what the most appropriate form of detection for this is.

**Comment by richard-jones** [comment]
To detect CC0:

“CC0”
A URL like this: https://creativecommons.org/publicdomain/zero/1.0/
And possibly “public domain”?

**Comment by emanuil-tolev** [comment]
I'd make the URL the least common denominator. We don't support confidence scoring or anything like that, so unless you're willing to say "if it doesn't say ```public domain``` then it's not CC0" I'd just go with the URL.

**Comment by richard-jones** [comment]
A couple of example PMCIDs that are CC0 for use in testing

PMC3970965
PMC3953412
PMC3945438

Note that URLs are not present in their XML licence declarations, so we will not be able to rely on that as the key indicator.

**Comment by richard-jones** [comment]
I've written and committed the code for this, but I'm on a train, so the testing is not so reliable.  Will revisit in a stable location.
