### ISSUE TITLE
service/runner.py can die if spreadsheet is malformed

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#66]
If you upload an invalid CSV (e.g. with too many or not enough values for the columns), ClCsv will throw an error, which ultimately kills the runner.

Not sure at what level we should handle this, but initially assigning to you, @emanuil-tolev, just as it kills the runner, which will prevent any further jobs getting processed - might be worth including an except block.  

I'll also have a think about how to handle invalid spreadsheets at the processing level.  Probably want to set the sheet's status to "error" or something.

**Comment by emanuil-tolev** [comment]
Hm, yeah. A general try/except is what I'll use in the runner, and set the status of the sheet to error, and log a magic number (and display the magic number on the page) - so that we can later sift the daemon logs for it. Any other ideas, throw them in here.

**Comment by richard-jones** [comment]
Actually, I have a general set of thoughts about this, because the oagr runner can also be killed by an untrapped exception.

In some cases this is bad - for example, if an email fails to send, I don't want it to kill the oagr processor.

In other cases, I'm not sure.  What if the exception is systematic, and the process dying is a warning to us that something needs to be looked at.

Perhaps this is tied quite closely to monitoring?  I have been thinking about trapping and storing exceptions that oagr throws, and allowing it to carry on working, but at the same time giving us a route to notice when it's mis-behaving.

What do you think?

Also, remember that exceptions in your runner might not be because of an error with the spreadsheet - is it therefore correct to mark the sheet as "error"?  Not sure, maybe that makes most sense to the user, even if it was our problem not theirs.

**Comment by emanuil-tolev** [comment]
Add an email logger so we get emailed all log messages. Then set the logging level to Critical. Then we'll know about exceptions?

**Comment by emanuil-tolev** [comment]
As an aside, this wouldn't work with the DOAJ because there are exceptions we haven't fixed (like query.py errors out on weird queries sometimes, and with 10k hits a day that's often enough). So if we do do this we'll feel compelled to fix all the exceptions that we let bubble up. If an email comes, we either have to fix the problem or commit a try/except to downgrade the exception to a log debug message (mask it). So if we're happy with that for this app, for now, then this seems like a good approach.

**Comment by emanuil-tolev** [comment]
> Add an email logger so we get emailed all log messages. Then set the logging level to Critical. Then we'll know about exceptions

So I've done this (in the develop branch already).

This is what we do now: https://github.com/CottageLabs/oacwellcome/blob/develop/service/runner.py#L14

The email logging of errors will only work in production mode. To test it, put DEBUG=False in your local.cfg .
