### ISSUE TITLE
Character encoding in csvs

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#73]
Excel seems to produce characters (especially £) which can't be read in.  Is there something we can do about this in ClCsv?

**Comment by emanuil-tolev** [comment]
oh god

**Comment by richard-jones** [comment]
Traceback (most recent call last):
  File "service/runner.py", line 20, in <module>
    run()
  File "service/runner.py", line 15, in run
    process_jobs()
  File "/opt/oacwellcome/src/oacwellcome/service/workflow.py", line 211, in process_jobs
    jobs = models.SpreadsheetJob.list_by_status("submitted")
  File "/opt/oacwellcome/src/oacwellcome/service/workflow.py", line 229, in process_job
    
  File "/opt/oacwellcome/src/oacwellcome/service/workflow.py", line 71, in parse_csv
    sheet = sheets.MasterSheet(path)
  File "/opt/oacwellcome/src/oacwellcome/service/sheets.py", line 48, in __init__
    self._sheet = clcsv.ClCsv(path)
  File "/opt/oacwellcome/src/oacwellcome/magnificent-octopus/octopus/lib/clcsv.py", line 26, in __init__
    self.read_file()
  File "/opt/oacwellcome/src/oacwellcome/magnificent-octopus/octopus/lib/clcsv.py", line 44, in read_file
    for row in reader:
  File "/opt/oacwellcome/src/oacwellcome/magnificent-octopus/octopus/lib/clcsv.py", line 237, in next
    row = self.reader.next()
  File "/opt/oacwellcome/src/oacwellcome/magnificent-octopus/octopus/lib/clcsv.py", line 223, in next
    val = self.reader.next()
  File "/opt/oacwellcome/lib/python2.7/codecs.py", line 681, in next
    return self.reader.next()
  File "/opt/oacwellcome/lib/python2.7/codecs.py", line 612, in next
    line = self.readline()
  File "/opt/oacwellcome/lib/python2.7/codecs.py", line 527, in readline
    data = self.read(readsize, firstline=True)
  File "/opt/oacwellcome/lib/python2.7/codecs.py", line 474, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa3 in position 134: invalid start byte

**Comment by richard-jones** [comment]
Oh man there's some bad stuff going on under the hood here.

I have started an effective fix for the character encoding issue, though this still has a way to go, but there are other nasty things that Excel does when it exports csvs.  In particular, I'm finding control characters kicking around in the data, which are doing bad things to the python csv reader.

Looks like a full solution will require some way of stripping those out or reverting them.  Some stuff in this SO:

http://stackoverflow.com/questions/6609895/efficiently-replace-bad-characters

**Comment by markmacgillivray** [comment]
Just in case it helps, here are some links to LEAPS stuff, there may be
useful things in there. In the end I believe it came down to building a
dictionary of rubbish and matching it out.

https://github.com/CottageLabs/leaps/blob/master/portality/view/leaps/imports.py

https://github.com/CottageLabs/leaps/blob/master/portality/view/leaps/exports.py

https://github.com/CottageLabs/leaps/blob/master/portality/util.py#L18

**Comment by richard-jones** [comment]
Great, thanks for those links.  I've also done pretty much the same thing, but learned a new thing.  In your code you use "windows-1252", but I found that "cp1252" gives better results for parsing windows-generated files.  I've also got iso-8859-2 in my stack of things to check.

**Comment by emanuil-tolev** [comment]
@richard-jones you should generally handle both. Tbh we should use a lib for this, some of my childhood was spent dealing with cp1251, the Cyrillic codepage, and there is a *long* list of codepages to try, as well as priority if you know the source is Western, Eastern European, East Asian..

**Comment by richard-jones** [comment]
Yup - actually I've made it so you can specify a list of potential encodings, or it will default to a common set.  If you happen to have a list of the common ones, then I can use that.

I wasn't able to find a lib that would just out the encodings for you, except chardet, which takes far too long to get results.

**Comment by richard-jones** [comment]
Ok, this is fixed - the csv parser now has a list of encodings to fall back to if the specified encoding (utf-8 by default) doesn't work.  It will keep trying until it finds one that works, or it runs out of options.

I have included cp1252, cp1251, windows-1252, windows-1251, utf-8, latin-1 and latin-2 in the list of encodings to try.  This covers everything in @markmacgillivray 's dewindows method, plus the cp* ones that I didn't know existed until yesterday!

**Comment by richard-jones** [comment]
Subsequent tests indicate that this problem as gone away with the encodings that we're currently using.  It may recur if csvs are uploaded with other encodings that we don't understand, but we now have a simple way of adding new ones, so shouldn't be a long-term issue.
