### ISSUE TITLE
Add OU CORE lookup support

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#75]
Query to see if identifiers are available in CORE, and therefore whether the content is archived in a repository

**Comment by markmacgillivray** [comment]
I have a core replica that is reliably queryable...

**Comment by richard-jones** [comment]
At the moment CORE is not queryable by DOI, so we can't do this directly, though we are ready to do when possible.  In the mean time, we may want to consider looking at @markmacgillivray 's mirror...

**Comment by emanuil-tolev** [comment]
This issue was moved to CottageLabs/lantern#7
