### ISSUE TITLE
Lookup embargoes in Sherpa

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#76]
See what information about embargoes we can get from Sherpa, and report on that.

**Comment by richard-jones** [comment]
I've now added to the romeo client library to look for and extract embargoes.  Not yet built into the compliance app - likely to be moved into a fork for the monitor project/ongoing development.

**Comment by emanuil-tolev** [comment]
This issue was moved to CottageLabs/lantern#6
