### ISSUE TITLE
Create user upload interface

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#8]
The user must provide us with

1. a CSV version of the Wellcome compliance spreadsheet
2. A contact email

This will upload a copy of the csv (which we should keep on disk, and offer a download link for), and either create a record in the index for the upload (see #4 ) or trigger a task which will do so shortly (see #13 ).

At this stage it will also be necessary to normalise any incoming identifiers from the spreadsheet as per #14 

Upon completion of upload, the user should be given a unique url at which they can view the status of their job, and a confirmation email of the same.  See #9

**Comment by Nimphal** [comment]
Does the email need to say anything more specific than "Thank you for your upload. You can view the progress of your upload at" plus the url?

**Comment by richard-jones** [comment]
I don't think so, at least at the moment.

I would also suggest that we snag the emailing functionality from DOAJ, and have the email text itself in a jinja template, so it will be nice and easy to modify later:

https://github.com/DOAJ/doaj/blob/develop/portality/app_email.py

**Comment by Nimphal** [comment]
Emailing functionality snagged, app updated and email template created.

**Comment by richard-jones** [comment]
Decided that this page should actually be the root page on the site - no need for a home page at this stage.

**Comment by richard-jones** [comment]
Also, notes for things to fix:

1. Disable the submit button until a file has been specified and an email address has been entered
2. Validate the email address, and ensure that it's a real address - if validation fails, return the user to the page with a suitable error

**Comment by Nimphal** [comment]
Is it necessary to disable the submit button provided validation is there? Just asking because it would involve some JS and so far the interface has not included any JS, so it might be overcomplicating.
