### ISSUE TITLE
[OAG] Add ability to invalidate cache for specific identifiers via the API

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/oacwellcome#81]

**Comment by emanuil-tolev** [comment]
@richard-jones howopenisit.org caching its results might get a bit out of hand in the coming days as we repeatedly run sheets through the system, so adding this issue, will implement ASAP (so next week). Will probably just be a ```"disable_cache": true``` in the request to OAG so should be very easy to add to OAGR.

**Comment by richard-jones** [comment]
Decided against doing this.
