### ISSUE TITLE
Options for upload/output spreadsheet formats

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#82]
The current version of the system is tailored specifically to the Wellcome Master spreadsheet format, which means that it won't understand columns that are no defined there, and it will not reflect them back at the user.

Consider the following options:

1. Support arbitrary columns and enhance/overlay with compliance data.  This opens us up to storing arbitrary content, which would be bad, and the processing chain is quite complex for producing the output sheets.  May be more trouble than it is worth

2. Support defined formats that users specify at upload.  We could then validate sheets before accepting them, and there would be no ambiguity in what is output.

3. Output only the identifiers and compliance data.  This removes ambiguity over what the user will get back and absolves us from having to deal with user's additional spreadsheet contents, but means the user must stitch the sheets back together themselves, so reduces overall user friendly-ness.

**Comment by richard-jones** [comment]
Probably we should implement a file size limit alongside this

**Comment by richard-jones** [comment]
Overall, I like (2) with the option to have (3) as the default format.

**Comment by emanuil-tolev** [comment]
This issue was moved to CottageLabs/lantern#3
